### ISSUE TITLE
reopen app. error occured.

### ISSUE THREAD

**Issue by nasum** [h3poteto/whalebird-desktop#104]
![image](https://user-images.githubusercontent.com/1456806/37822150-0339ac94-2ec9-11e8-8c8b-cdbd7a78afe6.png)

```javascript
Uncaught Exception:
Error: Object has been destroyed
    at WebContents.send (/Applications/whalebird.app/Contents/Resources/electron.asar/browser/api/web-contents.js:97:15)
    at D.start (/Applications/whalebird.app/Contents/Resources/app.asar/dist/electron/main.js:1:12149)
    at StreamingAPIConnection.listener.on (/Applications/whalebird.app/Contents/Resources/app.asar/dist/electron/main.js:1:26028)
    at emitOne (events.js:115:13)
    at StreamingAPIConnection.emit (events.js:210:7)
    at Parser.<anonymous> (/Applications/whalebird.app/Contents/Resources/app.asar/node_modules/mastodon-api/lib/streaming-api-connection.js:289:22)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser.parse (/Applications/whalebird.app/Contents/Resources/app.asar/node_modules/mastodon-api/lib/parser.js:76:34)
    at IncomingMessage.<anonymous> (/Applications/whalebird.app/Contents/Resources/app.asar/node_modules/mastodon-api/lib/streaming-api-connection.js:136:37)
```

**Comment by h3poteto** [comment]
I do not know how to reproduce this bug. In my macOS, I can reopen it normally.
Do you still occur it?
