### ISSUE TITLE
Hashtag streaming broken on Pleroma

### ISSUE THREAD

**Issue by logomancer** [h3poteto/whalebird-desktop#1206]
## Description
The client gives an error when attempting to stream a hashtag from a Pleroma instance.

## How To Reproduce
1. With a logged-in Pleroma account, select the hashtag search.
2. Search for a hashtag and wait for the search results.

## Expected results
Hashtag is streamed properly.

## Actual results
Error notification appears reading "Failed to start streaming". Tailing `~/.config/Whalebird/log.log` showed a stream of the following errors for as long as the hashtag window was selected:

```
[2020-01-05 17:38:13.748] [error] Error: Unexpected server response: 426
    at ClientRequest.<anonymous> (/usr/lib/whalebird-desktop/resources/app.asar/node_modules/megalodon/node_modules/ws/lib/websocket.js:579:7)
    at ClientRequest.emit (events.js:200:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:23)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:452:22)
    at TLSSocket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:210:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:166:17)
```

## Your Environment
 - OS: Arch Linux
 - Whalebird Version: package `whalebird-desktop-git` from AUR, version `3.0.2+r31+g9d85af23-1` presumably built from git commit 9d85af2. Also seen on `whalebird-bin` AUR package, version 3.0.2-1.
 - Instance: Private instance running Pleroma 1.1.6.

**Comment by h3poteto** [comment]
I can start hashtag streaming on my computer.
```
[2020-01-06 20:24:42.276] [info] /streaming/?stream=public started
[2020-01-06 22:16:23.950] [info] /streaming/?stream=hashtag&tag=whalebird started
[2020-01-06 22:17:20.790] [info] streaming stopped
```

And HTTP status 426 is `Upgrade Required`: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426
So are there any errors in your Pleroma server?

**Comment by logomancer** [comment]
No errors were recorded at the time of the client error. I've since updated to 1.1.7 and been able to reproduce the issue. Since HTTP 426 is a request to upgrade to the HTTP2 protocol, could it be an issue with not handling HTTP2 over the WebSocket?

**Comment by h3poteto** [comment]
My Pleroma server version is 1.1.7, but I can't reproduce this issue.

> could it be an issue with not handling HTTP2 over the WebSocket?

I had never considered it. Are you using HTTP2 on your Pleroma server? Could you please show me your nginx config if possible?
