### ISSUE TITLE
Unable to connect to my self hosted Pleroma instance

### ISSUE THREAD

**Issue by zell-mbc** [h3poteto/whalebird-desktop#1284]
## Description
When I try to connect to my self hosted Pleroma instance I receive the error message below:
![image](https://user-images.githubusercontent.com/29018767/75347223-9bcaeb00-58a0-11ea-9f5d-b2457ac7c106.png)

This URL works just fine with Firefox

Tried "no proxy" and "use system proxy" without any effect
## Your Environment
 - OS: ArchLinux
 - Whalebird Version: 3.1.0
 - Instance: social.zell-mbc.com

**Comment by h3poteto** [comment]
![Screenshot from 2020-02-27 00-13-57](https://user-images.githubusercontent.com/4631959/75358339-1114db00-58f6-11ea-982c-d2c540ae760b.png)

 I can connect.

**Comment by zell-mbc** [comment]
Now this is interesting? Are there any logs I could check which help identify what's going wrong? I can ping the URL, and my browser can find it as well. What else can go wrong?

**Comment by h3poteto** [comment]
In Linux, the logs are stored in `$HOME/.config/Whalebird/log.log`. I don't know why you can not connect your server only from Whalebird.

**Comment by zell-mbc** [comment]
Does this provide a hint? I got quite a few of these in my log.

```
[2020-02-27 17:55:39.848] [error] Error: empty
    at /opt/Whalebird/resources/app.asar/dist/electron/main.js:1:155926
    at newArguments.<computed> (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/Whalebird/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/opt/Whalebird/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/opt/Whalebird/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:498:34)
```

**Comment by h3poteto** [comment]
This error is no problem. This error happens when the database does not exist. If there is no database it will be created automatically, so no problem.

**Comment by ookangzheng** [comment]
Your site aren't redirect from HTTP to HTTPS, maybe this cause this issue
