### ISSUE TITLE
Browser window sometimes doesn't open when entered instance hostname and clicked Login

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [h3poteto/whalebird-desktop#1674]
## Description
no login / add account gui functionality

## How To Reproduce
1.
```
$ sudo snap install whalebird
whalebird 4.2.0 from AkiraFukushima (h3poteto) installed
````
2. launch whalebird from ubuntu mate menu
3. explore all of the guis of whalebird
4. FAIL

## Your Environment
 - OS: ubuntu bionic
 - Whalebird Version: 4.2.0
 - Instance: pleroma.site

**Comment by h3poteto** [comment]
Could you please attach your screenshot of Whalebird after launch?
Did Whalebird say any errors?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
btw fyi i did

```
sudo snap install whalebird
whalebird 4.2.0 from AkiraFukushima (h3poteto) installed
sudo snap remove whalebird
whalebird removed
sudo snap install whalebird
whalebird 4.2.0 from AkiraFukushima (h3poteto) installed
whoami
user
whalebird 
Gtk-Message: 14:33:00.503: Failed to load module "appmenu-gtk-module"
14:33:00.538 › Error: ENOENT: no such file or directory, open '/home/user/snap/whalebird/91/.config/Whalebird/db/unread_notification.db'
[Error: ENOENT: no such file or directory, open '/home/user/snap/whalebird/91/.config/Whalebird/cache/hashtag.db'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/snap/whalebird/91/.config/Whalebird/cache/hashtag.db'
}
14:33:00.560 › Error: empty
    at /snap/whalebird/91/resources/app.asar/dist/electron/main.js:1:164932
    at newArguments.<computed> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:498:34)
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
/usr/share/libdrm/amdgpu.ids: No such file or directory
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
14:33:00.621 › System proxy configuration: DIRECT
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
/usr/share/libdrm/amdgpu.ids: No such file or directory
14:33:01.137 › Error: empty
    at /snap/whalebird/91/resources/app.asar/dist/electron/main.js:1:164932
    at newArguments.<computed> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:498:34)
```

And initial window shot is:

![image](https://user-images.githubusercontent.com/19966907/89260845-a82d4e00-d65f-11ea-9565-fd037023cd25.png)

**Comment by nonlinear-chaos-order-etc-etal** [comment]
I can install a debugging version if you provide me with short instructions. I am not familiar with Electron.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Also, there is an error shown in Prefs/Account:

img:
![image](https://user-images.githubusercontent.com/19966907/89261415-9ac49380-d660-11ea-9d32-ec97a94314e2.png)

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Also, whalebird doesn't exit on window close. Log after window close, a term where whalebird runs in fg:

```
^C^Z
[1]+  Stopped    whalebird
Ok
bg
[1]+ whalebird &
Ok
ps
  PID TTY          TIME CMD
25625 pts/5    00:00:00 bash
25644 pts/5    00:00:03 whalebird
25854 pts/5    00:00:00 whalebird
25855 pts/5    00:00:00 whalebird
25900 pts/5    00:00:00 whalebird
25928 pts/5    00:00:05 whalebird
25971 pts/5    00:00:01 whalebird
28013 pts/5    00:00:00 ps
Ok
killall whalebird
Ok
[25644:0804/144357.620693:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
ps
  PID TTY          TIME CMD
25625 pts/5    00:00:00 bash
32559 pts/5    00:00:00 ps
[1]+  Illegal instruction                     (core dumped) whalebird
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Here is a `/home/user/snap/whalebird/91/.config/Whalebird/logs/main.log`:

```
[2020-08-04 15:01:21.257] [error] Error: ENOENT: no such file or directory, open '/home/user/snap/whalebird/91/.config/Whalebird/db/unread_notification.db'
[2020-08-04 15:01:21.330] [error] Error: empty
    at /snap/whalebird/91/resources/app.asar/dist/electron/main.js:1:164932
    at newArguments.<computed> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:498:34)
[2020-08-04 15:01:21.724] [info] System proxy configuration: DIRECT
[2020-08-04 15:01:22.901] [error] Error: empty
    at /snap/whalebird/91/resources/app.asar/dist/electron/main.js:1:164932
    at newArguments.<computed> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/91/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/91/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:498:34)
```

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Noticed the tray icon. After tray->Quit it exits cleanly.

**Comment by h3poteto** [comment]
It seems like that it is working no problem.
Please type your mastodon/pleroma/misskey server domain name to login in initial window.

I'm not sure what do you think is the problem.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
I type my Pleroma server pleroma.site into the field, it says confirmed and does nothing - this was the case multiple times before now.

Now I received browser oauth window and all is okay. Not sure where was the problem.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Bug confirmed. Browser window sometimes never opens when Login pressed.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Browser opened with second attempt at clicking Login. Did not open on the first attempt.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
And panel with Login button goesn't get replaced with the next screen that tells how to manually open the auth URL.

**Comment by h3poteto** [comment]
Could you please show me your screenshot of Whalebird?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Screen before Search click:

img1:
![image](https://user-images.githubusercontent.com/19966907/89642011-80e7b280-d8e5-11ea-9a93-7e5f05f856a9.png)

Screen after Search click:

img2:
![image](https://user-images.githubusercontent.com/19966907/89642045-98bf3680-d8e5-11ea-9d65-ff3b5c5186ef.png)

**Comment by h3poteto** [comment]
What happens when you click login button?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
The brightness of the window dims, and then error box appears approx. "Failed to authorized URL" and then disappears, and then brightness of the window restores to normal. Nothing other happens, no OS browser window appears.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Screen after Login clicked and the above sequence completed:

img:
![image](https://user-images.githubusercontent.com/19966907/89708507-793e1180-d9aa-11ea-863f-791bcaf52977.png)

**Comment by h3poteto** [comment]
Hmm...
I can't reproduce it.

When I try to login to pleroma.site,
![Screenshot from 2020-08-08 22-24-39](https://user-images.githubusercontent.com/4631959/89711577-165a7380-d9c6-11ea-90bd-f9904991bc03.png)

![Screenshot from 2020-08-08 22-24-43](https://user-images.githubusercontent.com/4631959/89711579-1eb2ae80-d9c6-11ea-9606-9cd99fb5d865.png)

 I can confirm the domain, 

![Screenshot from 2020-08-08 22-24-49](https://user-images.githubusercontent.com/4631959/89711590-34c06f00-d9c6-11ea-9d5f-8a3fe6823f92.png)

and after I click login button, Whalebird displayed this page. And my browser is opened and authorization page is displayed.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
So, this defect needs more info... Maybe some developer will elaborate on it. I am currently lazy to do this as this defect is not critical for Whalebird function. So closing it.
