### ISSUE TITLE
Defect: whalebird process silently exits immediately after launch

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [h3poteto/whalebird-desktop#2025]
## Description

The whalebird process silently exits immediately after launch. It doesn't show any GUI.

```
whalebird
Ok
ps auxwww | grep whale
user      141328  0.0  0.0   8880   656 pts/8    S+   04:02   0:00 grep whale
Ok
```

## How To Reproduce
1. ???

## Your Environment
 - OS: Ubuntu 20.04.x
 - Whalebird Version: 4.3.1
```
snap info whalebird
name:      whalebird
summary:   Whalebird
publisher: AkiraFukushima (h3poteto)
store-url: https://snapcraft.io/whalebird
contact:   https://whalebird.social/desktop/contacts/new
license:   unset
description: |
  An Electron based Mastodon client for Windows, Mac and Linux
commands:
  - whalebird
snap-id:      wtlQQaUNASoWxqfxRflcRjU3au6cQ3X0
tracking:     latest/stable
refresh-date: 14 days ago, at 18:53 +08
channels:
  latest/stable:    4.3.1 2020-12-03 (97) 84MB -
  latest/candidate: 4.3.1 2020-12-03 (97) 84MB -
  latest/beta:      4.3.1 2020-12-02 (97) 84MB -
  latest/edge:      ^                          
installed:          4.3.1            (97) 84MB -
```

 - Instance: 3 accounts: shitposter.club, pleroma.site, mastodon.ml

**Comment by h3poteto** [comment]
Hmm...I don't know what happens.
Does Whalebird say any log when exit?

**Comment by nonlinear-chaos-order-etc-etal** [comment]
* whalebird without options produces no logs (at least I haven't found them)
 * whalebird --no-sandbox:
 
 ```
/snap/whalebird/current/whalebird --no-sandbox
17:44:51.398 › Error: ENOENT: no such file or directory, open '/home/user/.config/Whalebird/db/unread_notification.db'
[Error: ENOENT: no such file or directory, open '/home/user/.config/Whalebird/cache/hashtag.db'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/.config/Whalebird/cache/hashtag.db'
}
17:44:51.890 › Error: empty
    at /snap/whalebird/97/resources/app.asar/dist/electron/main.js:1:177722
    at newArguments.<computed> (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:498:34)
(node:784317) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
17:44:52.382 › System proxy configuration: DIRECT
Error occurred in handler for 'list-accounts': j [Error]: empty
    at /snap/whalebird/97/resources/app.asar/dist/electron/main.js:1:177722
    at newArguments.<computed> (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/97/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/97/resources/app.asar/node_modules/async/lib/async.js:498:34)
```

--no-sandbox also shows a server login dialog.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
At least it works okay in `--no-sandbox` mode when launched as `/snap/whalebird/current/whalebird`

**Comment by nonlinear-chaos-order-etc-etal** [comment]
So this is a workaround

**Comment by nonlinear-chaos-order-etc-etal** [comment]
I upgraded to snap --stable 4.3.2 and this doesn't trigger anymore, even if without --no-sandbox
