### ISSUE TITLE
Whalebird crash: testcase for a "full image save as..." crash

### ISSUE THREAD

**Issue by ANANTASHESHALOKAGREENTARAEGPTRANSHOLON** [h3poteto/whalebird-desktop#2558]
## Description

Whalebird crashes on Full Image view -> Save image as... click.

## How To Reproduce

Whalebird crash: testcase for a "full image save as..." crash

### Step 1. 

```
‎sudo snap install whalebird
‎whalebird 4.4.1 from AkiraFukushima (h3poteto) installed
Ok
lsb_release -dc
Description:	Ubuntu 18.04.5 LTS
Codename:	bionic
Ok
mate-about --version
MATE Desktop Environment 1.20.1
Ok
ulimit -c unlimited
Ok
ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63504
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63504
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
Ok
pwd
/home/user/tmp/test1
Ok
ls -alh
итого 8.0K
drwxrwxr-x 2 user user 4.0K Jul 19 08:38 .
drwxrwxr-x 4 user user 4.0K Jul 19 08:38 ..
Ok
whoami
user
Ok
whalebird 
Gtk-Message: 08:42:04.579: Failed to load module "appmenu-gtk-module"

(whalebird:23127): GdkPixbuf-WARNING **: 08:42:04.585: Cannot open pixbuf loader module file '/home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
GLib-GIO-Message: 08:42:04.619: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
/usr/share/libdrm/amdgpu.ids: No such file or directory
08:42:04.850 › System proxy configuration: DIRECT
Error occurred in handler for 'get-unread-notification': ae [Error]: empty
    at /snap/whalebird/102/resources/app.asar/dist/electron/main.js:1:235064
    at newArguments.<computed> (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:498:34)
08:42:06.811 › user streaming is started
08:42:07.982 › user streaming is started
08:42:14.155 › local streaming is started
```

### Step 2. 

 * click at Whalebird window, click whalebird -> Exit, wait for it to close.
 * at terminal, see the PS1:

```
Ok
ps auxwww|grep whalebird
user     23349  0.0  0.0  15660  1052 pts/5    S+   08:44   0:00 grep --color=auto whalebird
Ok
gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache

Command 'gdk-pixbuf-query-loaders' not found, but can be installed with:

sudo apt install libgdk-pixbuf2.0-dev
```

Under root:

```
sudo apt install libgdk-pixbuf2.0-dev
```

Under user `user`:

```
whoami
user
Ok
gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
Ok
ls -al /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
-rw-rw-r-- 1 user user 3515 Jul 19 08:48 /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
Ok
ls -al /home/user/snap/whalebird/common/.cache/
итого 20
drwxrwxr-x  4 user user 4096 Jul 19 08:47 .
drwxr-xr-x  3 user user 4096 Jul 19 07:53 ..
drwxr-xr-x  2 user user 4096 Jul 19 07:53 fontconfig
-rw-rw-r--  1 user user 3515 Jul 19 08:48 gdk-pixbuf-loaders.cache
drwxr-xr-x 51 user user 4096 Jul 19 08:10 mesa_shader_cache
Ok
ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63504
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63504
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
Ok
whalebird 
Gtk-Message: 08:49:53.330: Failed to load module "appmenu-gtk-module"
GLib-GIO-Message: 08:49:53.365: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
Ok
aptitude search appmenu-gtk-module
i A appmenu-gtk-module-common                                                                        - Common files for GtkMenuShell D-Bus exporter                                                               
v   appmenu-gtk-module-common:i386                                                                   -                                                                                                            
Ok
````

Here, whalebird process exited immediately after launch:

```
ps auxwww|grep whalebird
user     26081  0.0  0.0  15660  1052 pts/5    S+   08:52   0:00 grep --color=auto whalebird
Ok
```

Then, we delete the `/home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache` file:

```
rm -v /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
deleted [...]
Ok
whalebird 
Gtk-Message: 08:53:21.132: Failed to load module "appmenu-gtk-module"

(whalebird:26102): GdkPixbuf-WARNING **: 08:53:21.138: Cannot open pixbuf loader module file '/home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
GLib-GIO-Message: 08:53:21.167: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
/usr/share/libdrm/amdgpu.ids: No such file or directory
08:53:21.363 › System proxy configuration: DIRECT
Error occurred in handler for 'get-unread-notification': ae [Error]: empty
    at /snap/whalebird/102/resources/app.asar/dist/electron/main.js:1:235064
    at newArguments.<computed> (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:498:34)
08:53:23.353 › user streaming is started
08:53:24.422 › user streaming is started
08:53:30.624 › local streaming is started
```

Then, at main Whalebird GUI window, we open URL https://toast.cafe/objects/8bcfaed6-b13a-419f-82f5-afb28117bd6d and 
left-click the image thumb. On full image view, we right click the image and click "Save image as...",
and Whalebird crashes.

Terminal log:

```
08:54:48.957 › streaming stopped
Error: Can't insert key animearmpits, it violates the unique constraint
    at _AVLTree.insert (/snap/whalebird/102/resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:273:19)
    at AVLTree.insert (/snap/whalebird/102/resources/app.asar/node_modules/binary-search-tree/lib/avltree.js:307:27)
    at Index.insert (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/indexes.js:77:15)
    at Datastore.addToIndexes (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:180:29)
    at Datastore._insertInCache (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:402:10)
    at Datastore._insert (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:348:10)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/executor.js:40:13
    at Immediate.process (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:731:21)
    at processImmediate (internal/timers.js:461:21) {
  key: 'animearmpits',
  errorType: 'uniqueViolated'
}
Error occurred in handler for 'get-unread-notification': ae [Error]: empty
    at /snap/whalebird/102/resources/app.asar/dist/electron/main.js:1:235064
    at newArguments.<computed> (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:520:14)
    at callback (/snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:130:20)
    at /snap/whalebird/102/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/snap/whalebird/102/resources/app.asar/node_modules/async/lib/async.js:498:34)
08:54:55.775 › Error: spawn aplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
08:54:56.143 › local streaming is started
08:54:56.573 › Error: spawn aplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
08:55:10.708 › Error: spawn aplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

(whalebird:26102): GdkPixbuf-WARNING **: 08:55:38.771: Cannot open pixbuf loader module file '/home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

(whalebird:26102): Gtk-WARNING **: 08:55:38.771: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(whalebird:26102): GdkPixbuf-WARNING **: 08:55:38.771: Cannot open pixbuf loader module file '/home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/user/snap/whalebird/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /snap/whalebird/102/data-dir/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Аварийный останов (стек памяти сброшен на диск) [ == 'Failure stop (core dumped to disk)' ]
Ok
ls -al
итого 24
drwxrwxr-x 2 user user  4096 Jul 19 08:58 .
drwxrwxr-x 4 user user  4096 Jul 19 08:38 ..
-rw-rw-r-- 1 user user 12469 Jul 19 08:58 testcase.txt
Ok
ulimit -c
unlimited
Ok
```

Whalebird about box:

![image](https://user-images.githubusercontent.com/1694903/126088596-d9343e55-b9f5-480e-8985-5ddbf41ee9ab.png)

## Your Environment
 - OS: Ubuntu 18.04.5 LTS
 - Whalebird Version: 4.4.1
 - Instance: mastodon.ml

**Comment by h3poteto** [comment]
Hmm... I can't reproduce it.
On my computer, I can save images.
