### ISSUE TITLE
Can not post toot on friends.nico

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#361]
## Description
I can not post toot in friends.nico.
I got error:

```
  [14:15:44.059] [error] Error: JSON decode error: Mastodon HTTP response body was not valid JSON
      at Function.makeMastodonError (/Users/akirafukushima/.akira/src/github.com/h3poteto/whalebird-desktop/node_modules/mastodon-api/lib/helpers.js:86:23)
      at Request.<anonymous> (/Users/akirafukushima/.akira/src/github.com/h3poteto/whalebird-desktop/node_modules/mastodon-api/lib/mastodon.js:269:57)
      at emitOne (events.js:120:20)
      at Request.emit (events.js:210:7)
      at IncomingMessage.<anonymous> (/Users/akirafukushima/.akira/src/github.com/h3poteto/whalebird-desktop/node_modules/request/request.js:1085:12)
      at Object.onceWrapper (events.js:314:30)
      at emitNone (events.js:110:20)
      at IncomingMessage.emit (events.js:207:7)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

## How To Reproduce
1. Create an account in friends.nico
2. Sign in to friends.nico through Whalebird
3. Post new toot

## Your Environment
 - OS: MacOS
 - Whalebird Version: 1.2.0
 - Instance: friends.nico

**Comment by h3poteto** [comment]
Now, I can post toot with curl:

```
$ curl -X POST -Ss https://friends.nico/api/v1/statuses \
  --header "Authorization: Bearer ${ACCESS_TOKEN}" --header "User-Agent: node-mastodon-client" \
  -d "status=${STATUS}"
```

but, I got error using node:

```javascript
const Mastodon = require('./node_modules/mastodon-api/lib/mastodon.js')

const baseUrl = 'https://friends.nico'

let client = new Mastodon({
  access_token: 'sample token',
  api_url: 'https://friends.nico/api/v1'
})

client.post('/statuses', {
  status: 'hoge'
}, (err, data, res) => {
  console.log(data)
  console.log(res)
  if (err) console.error(err)
})
```

**Comment by h3poteto** [comment]
Now `mastodon-api` posts form data using query parameters:
https://github.com/vanita5/mastodon-api/blob/master/src/mastodon.js#L165

But, it is not REST. I think if we use body when post form, it is succeed.

**Comment by h3poteto** [comment]
I see, may be I have to change api client.

**Comment by h3poteto** [comment]
I created new mastodon api client library which name is megalodon: https://github.com/h3poteto/megalodon

And, I changed api client to megalodon: https://github.com/h3poteto/whalebird-desktop/pull/379
