### ISSUE TITLE
Calckey の対応 / Support for Calckey

### ISSUE THREAD

**Issue by fu-sen** [h3poteto/whalebird-desktop#4164]
## Describe
Misskey v12 派生の Calckey の日本サーバが誕生しています。今後サーバが増えそうなので、サポートしていただけるとよろしいかと思いました。
A Japanese server of Calckey derived from Misskey v12 is born. The number of server is likely to increase in the future, so I thought it would be nice if you could support it.

## Why
日本インスタンス Calckey.jp が立ち上がっています。今後インスタンスが増える可能性があります。
Japanese server Calckey.jp has been released. The number of servers may increase in the future.
Misskey v12 を維持しているところがあり、一定の定評があります。また Misskey v13 から Calckey への移行も可能です。
Some maintain Misskey v12 and have a certain reputation. It is also possible to migrate from Misskey v13 to Calckey.
海外ではアメリカなどでいくつかサーバができています。
Overseas, there are several servers in the US, etc.

API 仕様は Misskey v12 共通と作者情報なので、Calckey であれば Misskey v12 扱いにするだけでいけると思います。
Since the API specifications are common to Misskey v12 and author information, I think you can just treat Calckey as Misskey v12.
https://calckey.jp/api-doc

よろしくお願いいたします。

Update: Added English

**Comment by h3poteto** [comment]
次からで良いので，基本的にIssueは英語で書いてください．日本語話者以外の人からは，何が行われているのかまったくわからなくなってしまうので．

**Comment by h3poteto** [comment]
で，疑問なんですが，Misskey v12と同じであるなら，現状のWhalebirdのままでもそのまま使えそうな気がするんですが，なにか特別な対応をする必要があるんですか？

**Comment by fu-sen** [comment]
Calckey は Misskey v12 の派生ですが、現在のバージョンはv13です。それは何か解決のヒントになりますか？
Calckey is a derivative of Misskey v12, but the current version is v13. Does that give you any hint of a solution?

**Comment by h3poteto** [comment]
いえ，そもそも現状でWhalebirdからCalckeyは使えないということなんですか？そこがわからないんですが．

**Comment by fu-sen** [comment]
ええ、正常に登録できるならこんな issues 建てないので……
`calckey.jp` などを追加して `Login` ボタンを押した 2 回目の段階で `Failed to get authorize url` と表示されていて進めません。

**Comment by h3poteto** [comment]
その情報を一番先に書いてください……

**Comment by h3poteto** [comment]
Memo:
```
  Error occurred in handler for 'add-app': AxiosError: Request failed with status code 404
      at settle (/run/media/h3poteto/ssd1/dev/src/github.com/h3poteto/whalebird-desktop/node_modules/axios/dist/node/axios.cjs:1900:12)
      at IncomingMessage.handleStreamEnd (/run/media/h3poteto/ssd1/dev/src/github.com/h3poteto/whalebird-desktop/node_modules/axios/dist/node/axios.cjs:2944:11)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'ERR_BAD_REQUEST',
    config: {
      transitional: {
        silentJSONParsing: true,
        forcedJSONParsing: true,
        clarifyTimeoutError: false
      },
      adapter: [ 'xhr', 'http' ],
      transformRequest: [ [Function: transformRequest] ],
      transformResponse: [ [Function: transformResponse] ],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      env: { FormData: [Function], Blob: null },
      validateStatus: [Function: validateStatus],
      headers: AxiosHeaders {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/1.3.3',
        'Content-Length': '137',
        'Accept-Encoding': 'gzip, compress, deflate, br'
      },
      signal: AbortSignal { aborted: false },
      method: 'post',
      url: 'https://calckey.jp/api/v1/apps',
      data: '{"client_name":"Whalebird","redirect_uris":"urn:ietf:wg:oauth:2.0:oob","scopes":"read write follow","website":"https://whalebird.social"}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype] {
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)],
        prefinish: [Function: requestOnPrefinish]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'calckey.jp',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'calckey.jp',
        _readableState: [ReadableState],
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular *1],
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 891,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: false,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object],
        [Symbol(RequestTimeout)]: undefined
      },
      _header: 'POST /api/v1/apps HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.3.3\r\n' +
        'Content-Length: 137\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: calckey.jp\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype],
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype],
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        maxCachedSessions: 100,
        _sessionCache: [Object],
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/apps',
      _ended: true,
      res: IncomingMessage {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 4,
        _maxListeners: undefined,
        socket: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        rawHeaders: [Array],
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 404,
        statusMessage: 'Not Found',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular *1],
        responseUrl: 'https://calckey.jp/api/v1/apps',
        redirects: [],
        [Symbol(kCapture)]: false,
        [Symbol(kHeaders)]: [Object],
        [Symbol(kHeadersCount)]: 18,
        [Symbol(kTrailers)]: null,
        [Symbol(kTrailersCount)]: 0,
        [Symbol(RequestTimeout)]: undefined
      },
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'calckey.jp',
      protocol: 'https:',
      _redirectable: Writable {
        _writableState: [WritableState],
        _events: [Object: null prototype],
        _eventsCount: 3,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 137,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function (anonymous)],
        _currentRequest: [Circular *1],
        _currentUrl: 'https://calckey.jp/api/v1/apps',
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        'accept-encoding': [Array],
        host: [Array]
      }
    },
    response: {
      status: 404,
      statusText: 'Not Found',
      headers: AxiosHeaders {
        'alt-svc': 'h3=":443"; ma=2592000',
        'cache-control': 'private, max-age=0, must-revalidate',
        'content-length': '9',
        'content-type': 'text/plain; charset=utf-8',
        date: 'Sun, 05 Mar 2023 02:17:18 GMT',
        server: 'Caddy',
        'strict-transport-security': 'max-age=15552000; preload',
        vary: 'Origin',
        connection: 'close'
      },
      config: {
        transitional: [Object],
        adapter: [Array],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: Infinity,
        maxBodyLength: Infinity,
        env: [Object],
        validateStatus: [Function: validateStatus],
        headers: [AxiosHeaders],
        signal: [AbortSignal],
        method: 'post',
        url: 'https://calckey.jp/api/v1/apps',
        data: '{"client_name":"Whalebird","redirect_uris":"urn:ietf:wg:oauth:2.0:oob","scopes":"read write follow","website":"https://whalebird.social"}'
      },
      request: <ref *1> ClientRequest {
        _events: [Object: null prototype],
        _eventsCount: 7,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        socket: [TLSSocket],
        _header: 'POST /api/v1/apps HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'Content-Type: application/json\r\n' +
          'User-Agent: axios/1.3.3\r\n' +
          'Content-Length: 137\r\n' +
          'Accept-Encoding: gzip, compress, deflate, br\r\n' +
          'Host: calckey.jp\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _keepAliveTimeout: 0,
        _onPendingData: [Function: nop],
        agent: [Agent],
        socketPath: undefined,
        method: 'POST',
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        path: '/api/v1/apps',
        _ended: true,
        res: [IncomingMessage],
        aborted: false,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        reusedSocket: false,
        host: 'calckey.jp',
        protocol: 'https:',
        _redirectable: [Writable],
        [Symbol(kCapture)]: false,
        [Symbol(kNeedDrain)]: false,
        [Symbol(corked)]: 0,
        [Symbol(kOutHeaders)]: [Object: null prototype]
      },
      data: 'Not Found'
    }
  }
```

**Comment by h3poteto** [comment]
Calckey provides `/api/v1/instance`, so it is detected as Mastodon. That means Calckey API is not entirely the same as the Misskey v12.
https://calckey.jp/api/v1/instance

**Comment by ThatOneCalculator** [comment]
The software should be determined by nodeinfo.

**Comment by h3poteto** [comment]
Yeah, so I changed. https://github.com/h3poteto/megalodon/pull/1678

**Comment by ThatOneCalculator** [comment]
Nice! The new detector should also check for `calckey`, and for now use the `misskey` adapter if detected
