### ISSUE TITLE
Broken on Arm

### ISSUE THREAD

**Issue by craigevil** [h3poteto/whalebird-desktop#4217]
## Description

/home/craig/Downloads/Whalebird-5.0.2-linux-arm64/whalebird
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/craig/Downloads/Whalebird-5.0.2-linux-arm64/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/home/craig/Downloads/Whalebird-5.0.2-linux-arm64/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/home/craig/Downloads/Whalebird-5.0.2-linux-arm64/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

## How To Reproduce
1. Crash at startup using the bzr
2. Crash on startup using the flatpak on 5.0.2
3.

## Your Environment
 - OS: Debian GNU/Linux 12 (bookworm) aarch64
 - Whalebird Version: 5.0.2
 - Instance: [e.g. fosstodon.org

**Comment by craigevil** [comment]
Yes. 5.0.1 and below work, while anything above 5.0.1 result in the error in my first post.

**Comment by h3poteto** [comment]
Can you confirm this file? Does it exist?
`Whalebird-5.0.2-linux-arm64/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node`
