### ISSUE TITLE
Failed to launch on Ubuntu

### ISSUE THREAD

**Issue by FiSHYsolutions** [h3poteto/whalebird-desktop#4338]
after updating to whalebird v5.0.4 (snap) the app run's after start in the background. but there is no window anymore. and there is also no tray-icon anymore. after starting whalebird nothing happens in my GUI, but i got a process. using the CLI  is mandatory to close the app which is not mom-friendly.

got this after starting whalebird:
```
bash:~$ ps -ef | grep whalebird
user     560704       1  0 19:50 ?        00:00:01 /snap/whalebird/148/whalebird --no-sandbox --enable-crashpad
user     560758  560704  0 19:50 ?        00:00:00 /snap/whalebird/148/whalebird --type=zygote --no-zygote-sandbox --no-sandbox --enable-crashpad --enable-crashpad
user     560759  560704  0 19:50 ?        00:00:00 /snap/whalebird/148/whalebird --type=zygote --no-sandbox --enable-crashpad --enable-crashpad
user     560781  560758  0 19:50 ?        00:00:00 /snap/whalebird/148/whalebird --type=gpu-process --no-sandbox --enable-crashpad --enable-crash-reporter=8b2b4ed0-c901-4f97-a815-82c9d55d88d8,no_channel --user-data-dir=/home/user/snap/whalebird/148/.config/Whalebird --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,13435310964792908781,1296433906291422081,131072 --disable-features=SpareRendererForSitePerProcess
user     560793  560704  0 19:50 ?        00:00:00 /snap/whalebird/148/whalebird --type=utility --utility-sub-type=network.mojom.NetworkService --lang=de --service-sandbox-type=none --no-sandbox --enable-crashpad --enable-crash-reporter=8b2b4ed0-c901-4f97-a815-82c9d55d88d8,no_channel --user-data-dir=/home/user/snap/whalebird/148/.config/Whalebird --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,13435310964792908781,1296433906291422081,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad
user     561092  560681  0 19:55 pts/3    00:00:00 grep --color=auto whalebird
```

no GUI, no window.
i am so tired of that crap.
please do not release buggy updates. thank you very much.

```
bash:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```
```
bash:~$ xfce4-about -V
xfce4-about 4.16.1 (Xfce 4.16)

Copyright (c) 2008-2019
	Die Xfce-Entwicklungsmannschaft. Alle Rechte vorbehalten.

Probleme bitte unter <https://gitlab.xfce.org/xfce/libxfce4ui/-/issues> melden.
```
```
bash:~$ snap info whalebird
name:      whalebird
summary:   Whalebird
publisher: AkiraFukushima (h3poteto)
store-url: https://snapcraft.io/whalebird
contact:   https://whalebird.social/desktop/contacts/new
license:   unset
description: |
  An Electron-based Mastodon, Pleroma, and Misskey client for Windows, Mac, and Linux.
commands:
  - whalebird
snap-id:      wtlQQaUNASoWxqfxRflcRjU3au6cQ3X0
tracking:     latest/stable
refresh-date: heute um 19:48 CEST
channels:
  latest/stable:    5.0.4 2023-04-30 (148) 105MB -
  latest/candidate: 5.0.4 2023-04-30 (148) 105MB -
  latest/beta:      5.0.4 2023-04-30 (148) 105MB -
  latest/edge:      ↑                            
installed:          5.0.4            (148) 105MB -
```

**Comment by h3poteto** [comment]
Was 5.0.3 working correctly?

**Comment by FiSHYsolutions** [comment]
"correctly" is a big word but reverting the snap from v5.0.4 to v5.0.3 brings back the whalebirdwindow and the broken systray icon (with the open issue described in #4225).

**Comment by h3poteto** [comment]
Ah, I mean can you open the Whalebird window in v5.0.3. Yeah, I got it.

**Comment by h3poteto** [comment]
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.QKV75K)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/snap/whalebird/148/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/snap/whalebird/148/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)
```

**Comment by h3poteto** [comment]
The cause is https://github.com/WiseLibs/better-sqlite3/issues/990

**Comment by h3poteto** [comment]
@FiSHYsolutions Can you please try 5.0.5? It is released on the beta channel in snap-store.

**Comment by FiSHYsolutions** [comment]
v5.0.5 is working
