### ISSUE TITLE
Failed to launch on Ubuntu

### ISSUE THREAD

**Issue by FiSHYsolutions** [h3poteto/whalebird-desktop#4461]
after updating to whalebird v5.0.6 (snap) the app run's after start in the background. but there is no window anymore. and there is also no tray-icon anymore. after starting whalebird nothing happens in my GUI, but i got a process. using the CLI is mandatory to close the app which is not mom-friendly.

got this after starting whalebird:

```
bash:~$ ps -ef | grep whale
user    2708831       1 38 23:08 ?        00:00:01 /snap/whalebird/154/whalebird --no-sandbox --enable-crashpad
user    2708897 2708831  0 23:08 ?        00:00:00 /snap/whalebird/154/whalebird --type=zygote --no-zygote-sandbox --no-sandbox --enable-crashpad --enable-crashpad
user    2708898 2708831  0 23:08 ?        00:00:00 /snap/whalebird/154/whalebird --type=zygote --no-sandbox --enable-crashpad --enable-crashpad
user    2708921 2708897 22 23:08 ?        00:00:00 /snap/whalebird/154/whalebird --type=gpu-process --no-sandbox --enable-crashpad --enable-crash-reporter=8b2b4ed0-c901-4f97-a815-82c9d55d88d8,no_channel --user-data-dir=/home/user/snap/whalebird/154/.config/Whalebird --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,14864243877261720995,8290051994002445263,131072 --disable-features=SpareRendererForSitePerProcess
user    2708933 2708831 10 23:08 ?        00:00:00 /snap/whalebird/154/whalebird --type=utility --utility-sub-type=network.mojom.NetworkService --lang=de --service-sandbox-type=none --no-sandbox --enable-crashpad --enable-crash-reporter=8b2b4ed0-c901-4f97-a815-82c9d55d88d8,no_channel --user-data-dir=/home/winky/snap/whalebird/154/.config/Whalebird --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,14864243877261720995,8290051994002445263,131072 --disable-features=SpareRendererForSitePerProcess --enable-crashpad
user    2708945 2708803  0 23:08 pts/7    00:00:00 grep --color=auto whale
```

no GUI, no window.
we had the same issue already in #4338 
please do not release buggy updates. thank you very much.

```
bash:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

```
bash:~$ xfce4-about -V
xfce4-about 4.16.1 (Xfce 4.16)

Copyright (c) 2008-2019
	Die Xfce-Entwicklungsmannschaft. Alle Rechte vorbehalten.

Probleme bitte unter <https://gitlab.xfce.org/xfce/libxfce4ui/-/issues> melden.
```

```
bash:~$ snap info whalebird
name:      whalebird
summary:   Whalebird
publisher: AkiraFukushima (h3poteto)
store-url: https://snapcraft.io/whalebird
contact:   https://whalebird.social/desktop/contacts/new
license:   unset
description: |
  An Electron-based Mastodon, Pleroma, and Misskey client for Windows, Mac, and Linux.
commands:
  - whalebird
snap-id:      wtlQQaUNASoWxqfxRflcRjU3au6cQ3X0
tracking:     latest/stable
refresh-date: vor 2 Tagen, um 18:25 CEST
channels:
  latest/stable:    5.0.6 2023-06-11 (154) 105MB -
  latest/candidate: 5.0.6 2023-06-10 (154) 105MB -
  latest/beta:      5.0.6 2023-06-10 (154) 105MB -
  latest/edge:      5.0.6 2023-06-10 (154) 105MB -
installed:          5.0.6            (154) 105MB -
```

trying to start via CLI:

```
bash:~$ whalebird 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.qzYLbJ)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/snap/whalebird/154/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/snap/whalebird/154/resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

(whalebird:2709014): Gtk-WARNING **: 23:08:55.823: Theme parsing error: gtk.css:1374:85: 'font-feature-settings' is not a valid property name
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
^C
```

after reverting the snap to v5.0.5 everything works fine again (except the buggy trayicon already documented in #4225)

**Comment by h3poteto** [comment]
This is a better-sqlite3 issue.

> please do not release buggy updates.

This is an OSS project, so bugs may be included as more features are added. If you want this, I will not add any more features and I will not release any more.
