### ISSUE TITLE
EmptyRecordError error at startup

### ISSUE THREAD

**Issue by scampi** [h3poteto/whalebird-desktop#734]
## Description

With a fresh install, I get an `EmptyRecordError` logged to the console.

## How To Reproduce

Start app from the console and the following is logged. However, this doesn't seem to prevent the correct use of the app after that.

```
[17:01:51.120] [error] EmptyRecordError: empty
    at new t (/opt/Whalebird/resources/app.asar/dist/electron/main.js:1:54145)
    at /opt/Whalebird/resources/app.asar/dist/electron/main.js:1:49586
    at newArguments.(anonymous function) (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/executor.js:29:17)
    at Cursor.execFn (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:484:12)
    at callback (/opt/Whalebird/resources/app.asar/node_modules/nedb/lib/cursor.js:126:19)
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/cursor.js:193:12
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:329:14
    at Object.async.eachSeries (/opt/Whalebird/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:130:20)
    at /opt/Whalebird/resources/app.asar/node_modules/nedb/lib/datastore.js:323:11
    at fn (/opt/Whalebird/resources/app.asar/node_modules/nedb/node_modules/async/lib/async.js:582:34)
```

## Your Environment
 - OS: linux 4.19.1 on archlinux
 - Whalebird Version: 2.4.4-1
 - Instance: not relevant as I was not logged to an instance yet.

**Comment by h3poteto** [comment]
I think that this error does not affect the behavior of this application. This log is a log for debug, so users don't care about the error.
