### ISSUE TITLE
Update events leaking from closed WebSockets in Pleroma

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#804]
## Description
Ever since #786, I keep getting spurious `update` events from WebSockets every time I forcibly switch streaming in a Pleroma account. This happens *only* with Pleroma.

```
┏ Electron -------------------

  [00:41:29.775] [error] Error: Error parsing websocket reply: Error: Object has been destroyed
      at Parser.parser (/Users/amalia/Desktop/whalebird/node_modules/megalodon/lib/web_socket.js:163:32)
      at WebSocketConnection.<anonymous> (/Users/amalia/Desktop/whalebird/node_modules/megalodon/lib/web_socket.js:103:30)
      at WebSocketConnection.emit (events.js:182:13)
      at WebSocketConnection.processFrame (/Users/amalia/Desktop/whalebird/node_modules/websocket/lib/WebSocketConnection.js:554:26)
      at /Users/amalia/Desktop/whalebird/node_modules/websocket/lib/WebSocketConnection.js:323:40
      at process._tickCallback (internal/process/next_tick.js:61:11)
  
  
┗ ----------------------------
```

```
Uncaught Exception:
Error: Object has been destroyed
    at WebContents.send (/Users/amalia/Desktop/whalebird/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:100:15)
    at eval (webpack:///./src/main/index.js?:543:20)
    at WebSocket.eval (webpack:///./src/main/websocket.js?:47:9)
    at WebSocket.emit (events.js:182:13)
    at Parser.<anonymous> (/Users/amalia/Desktop/whalebird/node_modules/megalodon/lib/web_socket.js:120:19)
    at Parser.emit (events.js:182:13)
    at Parser.parser (/Users/amalia/Desktop/whalebird/node_modules/megalodon/lib/web_socket.js:163:18)
    at WebSocketConnection.<anonymous> (/Users/amalia/Desktop/whalebird/node_modules/megalodon/lib/web_socket.js:103:30)
    at WebSocketConnection.emit (events.js:182:13)
    at WebSocketConnection.processFrame (/Users/amalia/Desktop/whalebird/node_modules/websocket/lib/WebSocketConnection.js:554:26)
```

## How To Reproduce
1. Sign in to a Pleroma account.
2. Click the streaming button.
3. Make sure the socket has been restarted (Terminal output) and close Whalebird's window.

## Your Environment
 - OS: [e.g. MacOS] MacOS
 - Whalebird Version: [e.g. 1.0.0] 2.6.1-dev
 - Instance: [e.g. mastodon.social] pleroma.site

**Comment by h3poteto** [comment]
Oh, I didn't assume that it will be enabled in Pleroma. I will fix it.

**Comment by amyspark** [comment]
Another way (more reliable) is to do the following:
1. Sign in to a Mastodon account. (It's not necessary to use websockets for streaming.)
2. Change to a Pleroma account. If you read the console log, you'll see the Mastodon account's DM websocket hasn't been stopped (there are two "streaming stopped" events instead of three).
3. Close Whalebird, and wait.

**Comment by h3poteto** [comment]
Thank you for your step.

**Comment by h3poteto** [comment]
Just to confirm, do you import this changes #799 ?

**Comment by amyspark** [comment]
Typo here. Doesn't fix it, but it prevents DMs from being inserted in the timeline across accounts.
https://github.com/h3poteto/whalebird-desktop/blob/2b2ffc2c8dadf58fb1dca7ed57e9c480bb1f4a2c/src/renderer/store/TimelineSpace.js#L339
